function eNBs7D2Ds8DD2Ds0UEsQLearning181218 = importfileLog(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as a matrix.
%   ENBS7D2DS8DD2DS0UESQLEARNING181218 = IMPORTFILE(FILENAME) Reads data
%   from text file FILENAME for the default selection.
%
%   ENBS7D2DS8DD2DS0UESQLEARNING181218 = IMPORTFILE(FILENAME, STARTROW,
%   ENDROW) Reads data from rows STARTROW through ENDROW of text file
%   FILENAME.
%
% Example:
%   eNBs7D2Ds8DD2Ds0UEsQLearning181218 = importfile('1eNBs_7D2Ds_8DD2Ds_0UEs_QLearning_181218.dat', 2, 2853);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2018/12/18 14:43:55

%% Initialize variables.
delimiter = ',';
if nargin<=2
    startRow = 2;
    endRow = inf;
end

%% Read columns of data as text:
% For more information, see the TEXTSCAN documentation.
formatSpec = '%s%s%s%s%s%s%s%s%s%s%s%s%s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
textscan(fileID, '%[^\n\r]', startRow(1)-1, 'WhiteSpace', '', 'ReturnOnError', false);
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'TextType', 'string', 'ReturnOnError', false, 'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    textscan(fileID, '%[^\n\r]', startRow(block)-1, 'WhiteSpace', '', 'ReturnOnError', false);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'TextType', 'string', 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Convert the contents of columns containing numeric text to numbers.
% Replace non-numeric text with NaN.
raw = repmat({''},length(dataArray{1}),length(dataArray)-1);
for col=1:length(dataArray)-1
    raw(1:length(dataArray{col}),col) = mat2cell(dataArray{col}, ones(length(dataArray{col}), 1));
end
numericData = NaN(size(dataArray{1},1),size(dataArray,2));

for col=[1,2,3,4,5,6,7,8,9,10,11,12,13]
    % Converts text in the input cell array to numbers. Replaced non-numeric
    % text with NaN.
    rawData = dataArray{col};
    for row=1:size(rawData, 1)
        % Create a regular expression to detect and remove non-numeric prefixes and
        % suffixes.
        regexstr = '(?<prefix>.*?)(?<numbers>([-]*(\d+[\,]*)+[\.]{0,1}\d*[eEdD]{0,1}[-+]*\d*[i]{0,1})|([-]*(\d+[\,]*)*[\.]{1,1}\d+[eEdD]{0,1}[-+]*\d*[i]{0,1}))(?<suffix>.*)';
        try
            result = regexp(rawData(row), regexstr, 'names');
            numbers = result.numbers;
            
            % Detected commas in non-thousand locations.
            invalidThousandsSeparator = false;
            if numbers.contains(',')
                thousandsRegExp = '^\d+?(\,\d{3})*\.{0,1}\d*$';
                if isempty(regexp(numbers, thousandsRegExp, 'once'))
                    numbers = NaN;
                    invalidThousandsSeparator = true;
                end
            end
            % Convert numeric text to numbers.
            if ~invalidThousandsSeparator
                numbers = textscan(char(strrep(numbers, ',', '')), '%f');
                numericData(row, col) = numbers{1};
                raw{row, col} = numbers{1};
            end
        catch
            raw{row, col} = rawData{row};
        end
    end
end


%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
eNBs7D2Ds8DD2Ds0UEsQLearning181218 = table;
eNBs7D2Ds8DD2Ds0UEsQLearning181218.uniqueID = cell2mat(raw(:, 1));
eNBs7D2Ds8DD2Ds0UEsQLearning181218.txType = cell2mat(raw(:, 2));
eNBs7D2Ds8DD2Ds0UEsQLearning181218.txID = cell2mat(raw(:, 3));
eNBs7D2Ds8DD2Ds0UEsQLearning181218.rxType = cell2mat(raw(:, 4));
eNBs7D2Ds8DD2Ds0UEsQLearning181218.rxID = cell2mat(raw(:, 5));
eNBs7D2Ds8DD2Ds0UEsQLearning181218.pktNumber = cell2mat(raw(:, 6));
eNBs7D2Ds8DD2Ds0UEsQLearning181218.pktSize = cell2mat(raw(:, 7));
eNBs7D2Ds8DD2Ds0UEsQLearning181218.crtTS = cell2mat(raw(:, 8));
eNBs7D2Ds8DD2Ds0UEsQLearning181218.txTS = cell2mat(raw(:, 9));
eNBs7D2Ds8DD2Ds0UEsQLearning181218.rxTS = cell2mat(raw(:, 10));
eNBs7D2Ds8DD2Ds0UEsQLearning181218.delay = cell2mat(raw(:, 11));
eNBs7D2Ds8DD2Ds0UEsQLearning181218.bitTp = cell2mat(raw(:, 12));
eNBs7D2Ds8DD2Ds0UEsQLearning181218.pktErr = cell2mat(raw(:, 13));

